name: bot
version: 0.25.3
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
documentation: http://kevmoo.github.io/bot.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  bot_test: '>=0.1.5'
  browser: '>=0.9.0 <0.10.0'
  hop: '>=0.28.1+2'
  unittest: '>=0.9.0 <0.10.0'
